In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass odf milk',
'the glass of juice',
'the cup of teas',
'I am a good boy',
'I am a good developer',
'understand the meaning of word',
'your videos are good']

In [3]:
sent

['the glass odf milk',
 'the glass of juice',
 'the cup of teas',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
sent

['the glass odf milk',
 'the glass of juice',
 'the cup of teas',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3626, 4244, 1438, 2896],
 [3626, 4244, 6849, 4405],
 [3626, 6728, 6849, 6674],
 [402, 7245, 6940, 6981, 1844],
 [402, 7245, 6940, 6981, 6932],
 [2094, 3626, 5650, 6849, 4247],
 [6746, 4455, 670, 6981]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [8]:
import numpy as sequences

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3626 4244 1438 2896]
 [   0    0    0    0 3626 4244 6849 4405]
 [   0    0    0    0 3626 6728 6849 6674]
 [   0    0    0  402 7245 6940 6981 1844]
 [   0    0    0  402 7245 6940 6981 6932]
 [   0    0    0 2094 3626 5650 6849 4247]
 [   0    0    0    0 6746 4455  670 6981]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','loss')

/Users/vineethsai/Desktop/Projects/release_notes_classification/ReleaseNotesClassification/cluster-top-50/myenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


array([[-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.00462551,  0.01733105,  0.02946781,  0.00875302,  0.04130191,
        -0.02242649, -0.0113946 , -0.03430587,  0.04324121, -0.04170438],
       [ 0.01271004, -0.01591232,  0.03429503, -0.01200112, -0.01684722,
         0.01708671, -0.01556059,  0.00992528, -0.01482962, -0.02817189],
       [-0.02253779,  0.00601469,  0.02805755,  0.01158339,  0.02602022,
         0.044949  ,  0.03392745, -0.03887845

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3626, 4244, 1438, 2896], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.01121595,  0.00562698, -0.02482339, -0.00390681,  0.02821669,
        -0.04666364, -0.01023327, -0.0324261 ,  0.03372603, -0.02816912],
       [-0.00462551,  0.01733105,  0.02946781,  0.00875302,  0.04130191,
        -0.02242649, -0.0113946 , -0.03430587,  0.04324121, -0.04170438],
       [ 0.01271004, -0.01591232,  0.03429503, -0.01200112, -0.01684722,
         0.01708671, -0.01556059,  0.00992528, -0.01482962, -0.02817189],
       [-0.02253779,  0.00601469,  0.02805755,  0.01158339,  0.02602022,
         0.044949  ,  0.03392745, -0.03887845